// This file was autogenerated by F:\developer\f1\lib\closure\bin\build\depswriter.py.
// Please do not edit.
//goog.addDependency('../../app.js', ['f1.engine.Run', 'f1.engine.Track'], ['f1.engine.Car']);
goog.addDependency('../../../../src/Map.js',    ['f1.racing.src.Map'], []);
goog.addDependency('../../../../src/Point.js',  ['f1.racing.src.Point'], []);
goog.addDependency('../../../../src/Racing.js', ['f1.racing.src.Racing'], []);
goog.addDependency('../../../config/game_config.js', ['f1.racing.config.game_config'], []);
